title: <p align="center"> Uttam Sarkar </p>
logo: /assets/img/UttamSarkar_Photo.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
